---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: dash
    namespace: {{ .Release.Namespace }}
    labels:
        name: {{ include "pachyderm.fullname" . }}
        app: dash
        suite: pachyderm
        helm.sh/chart: {{ include "pachyderm.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
spec:
    selector:
        matchLabels:
            name: {{ include "pachyderm.fullname" . }}
            app: dash
            suite: pachyderm
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            name: dash
            namespace: {{ .Release.Namespace }}
            labels:
                app: dash
                suite: pachyderm
                name: {{ include "pachyderm.fullname" . }}
        spec:
{{- if .Values.nodeSelector }}
            nodeSelector:
{{ toYaml .Values.nodeSelector | indent 17 }}
{{- end }}
            containers:
              - name: dash
                image: pachyderm/dash:0.5.48
                ports:
                  - name: dash-http
                    containerPort: 8080
                    protocol: TCP
                imagePullPolicy: Always
                terminationMessagePath: /dev/termination-log
                terminationMessagePolicy: File
              - name: grpc-proxy
                image: pachyderm/grpc-proxy:0.4.10
                ports:
                  - name: grpc-proxy-http
                    containerPort: 8081
                    protocol: TCP
                imagePullPolicy: Always
                terminationMessagePath: /dev/termination-log
                terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            terminationGracePeriodSeconds: 30
