---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    labels:
        app: etcd
        suite: pachyderm
    name: {{ include "pachyderm.fullname" . }}
    namespace: {{ .Release.Namespace }}
parameters:
    type: gp2
provisioner: kubernetes.io/aws-ebs
