---
apiVersion: v1
kind: Secret
metadata:
  name: pachyderm-storage-secret
  namespace: {{ .Release.Namespace }}
  creationTimestamp: null
  labels:
    app: pachyderm-storage-secret
    suite: pachyderm
    helm.sh/chart: {{ include "pachyderm.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  amazon-bucket:  {{ required "amazon.bucket is required if amazon installation is specified." .Values.amazon.bucket | b64enc }}
  {{- if .Values.amazon.distribution }}
  amazon-distribution: {{ .Values.amazon.distribution | b64enc }}
  {{- else }}
  amazon-distribution: ""
  {{- end }}
  amazon-region: {{ required "amazon.region is required if amazon installation is specified." .Values.amazon.region | b64enc }}
  max-upload-parts: {{ .Values.amazon.maxUploadParts | b64enc }}
  part-size: {{ .Values.amazon.partSize | b64enc }} 
  retries: {{ .Values.amazon.retries | b64enc }}
  reverse: {{ .Values.amazon.reverse | b64enc }}
  timeout: {{ .Values.amazon.timeout | b64enc }}
  upload-acl: {{ .Values.amazon.uploadAcl | b64enc }}

