---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: pachd
    namespace: {{ .Release.Namespace }}
    labels:
        app: pachd
        suite: pachyderm
        chart: {{ include "pachyderm.chart" . }}
        managed-by: {{ .Release.Service }}
        instance: {{ .Release.Name }}
spec:
    replicas: {{ .Values.pachd.replicaCount }}
    selector:
        matchLabels:
            app: pachd
            suite: pachyderm
    template:
        metadata:
            name: pachd
            namespace: {{ .Release.Namespace }}
            labels:
                app: pachd
                suite: pachyderm
{{- if or .Values.etcd.annotations .Values.amazon.roleArn }}
            annotations:
{{- end }}
{{- if .Values.etcd.annotations }}
{{ toYaml .Values.etcd.annotations | indent 16 }}
{{- end }}
{{- if .Values.amazon.roleArn }}
                iam.amazonaws.com/role: {{ .Values.amazon.roleArn }}
{{- end }}
        spec:
            volumes:
              - name: pach-disk
                emptyDir: {}
              - name: pachyderm-storage-secret
                secret:
                    secretName: pachyderm-storage-secret
                    defaultMode: 420
{{- if .Values.tolerations }}
            tolerations:
{{ toYaml .Values.tolerations | indent 17 }}
{{- end }}
{{- if .Values.nodeSelector }}
            nodeSelector:
{{ toYaml .Values.nodeSelector | indent 17 }}
{{- end }}
            containers:
              - name: pachd
                image: '{{ .Values.pachd.image.repository }}:{{ .Values.pachd.image.tag }}'
                ports:
                  - name: api-grpc-port
                    containerPort: 650
                    protocol: TCP
                  - name: trace-port
                    containerPort: 651
                  - name: api-http-port
                    containerPort: 652
                    protocol: TCP
                  - name: peer-port
                    containerPort: 653
                    protocol: TCP
                  - name: api-git-port
                    containerPort: 655
                    protocol: TCP
                  - name: saml-port
                    containerPort: 654
                    protocol: TCP
                env:
                  - name: ETCD_SERVICE_HOST
                    value: "etcd.{{ .Release.Namespace }}"
                  - name: ETCD_SERVICE_PORT
                    value: "2379"
                  - name: PACH_ROOT
                    value: /pach
                  - name: ETCD_PREFIX
                  - name: NUM_SHARDS
                    value: {{ .Values.pachd.shards | quote }}
                  - name: STORAGE_BACKEND
                    value: AMAZON
                  - name: STORAGE_HOST_PATH
                  - name: WORKER_IMAGE
                    value: '{{ .Values.pachd.worker.repository }}:{{ .Values.pachd.worker.tag }}'
                  - name: IMAGE_PULL_SECRET
                  - name: WORKER_SIDECAR_IMAGE
                    value: '{{ .Values.pachd.image.repository }}:{{ .Values.pachd.image.tag }}'
                  - name: WORKER_IMAGE_PULL_POLICY
                    value: IfNotPresent
                  - name: PACHD_VERSION
                    value: {{ .Values.pachd.image.tag }}
                  - name: METRICS
                    value: "true"
                  - name: LOG_LEVEL
                    value: info
                  - name: BLOCK_CACHE_BYTES
                    value: {{ .Values.pachd.pfsCache }}
                  - name: IAM_ROLE
                    value: {{ .Values.amazon.roleArn }}
                  - name: NO_EXPOSE_DOCKER_SOCKET
                    value: "false"
                  - name: PACHYDERM_AUTHENTICATION_DISABLED_FOR_TESTING
                    value: "false"
                  - name: PACHD_POD_NAMESPACE
                    valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                  - name: PACHD_MEMORY_REQUEST
                    valueFrom:
                        resourceFieldRef:
                            containerName: pachd
                            resource: requests.memory
                  - name: EXPOSE_OBJECT_API
                    value: {{ .Values.pachd.exposeObjApi | quote }}
                  - name:  REQUIRE_CRITICAL_SERVERS_ONLY
                    value: {{ .Values.pachd.requireCriticalServersOnly | quote }}
                  - name: GOOGLE_BUCKET
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: google-bucket
                            optional: true
                  - name: GOOGLE_CRED
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: google-cred
                            optional: true
                  - name: MICROSOFT_CONTAINER
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: microsoft-container
                            optional: true
                  - name: MICROSOFT_ID
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: microsoft-id
                            optional: true
                  - name: MICROSOFT_SECRET
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: microsoft-secret
                            optional: true
                  - name: MINIO_BUCKET
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: minio-bucket
                            optional: true
                  - name: MINIO_ENDPOINT
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: minio-endpoint
                            optional: true
                  - name: MINIO_ID
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: minio-id
                            optional: true
                  - name: MINIO_SECRET
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: minio-secret
                            optional: true
                  - name: MINIO_SECURE
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: minio-secure
                            optional: true
                  - name: MINIO_SIGNATURE
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: minio-signature
                            optional: true
                  - name: AMAZON_REGION
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-region
                            optional: true
                  - name: AMAZON_BUCKET
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-bucket
                            optional: true
                  - name: AMAZON_ID
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-id
                            optional: true
                  - name: AMAZON_SECRET
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-secret
                            optional: true
                  - name: AMAZON_TOKEN
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-token
                            optional: true
                  - name: AMAZON_VAULT_ADDR
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-vault-addr
                            optional: true
                  - name: AMAZON_VAULT_ROLE
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-vault-role
                            optional: true
                  - name: AMAZON_VAULT_TOKEN
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-vault-token
                            optional: true
                  - name: AMAZON_DISTRIBUTION
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: amazon-distribution
                            optional: true
                  - name: CUSTOM_ENDPOINT
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: custom-endpoint
                            optional: true
                  - name: RETRIES
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: retries
                            optional: true
                  - name: TIMEOUT
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: timeout
                            optional: true
                  - name: UPLOAD_ACL
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: upload-acl
                            optional: true
                  - name: REVERSE
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: reverse
                            optional: true
                  - name: PART_SIZE
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: part-size
                            optional: true
                  - name: MAX_UPLOAD_PARTS
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: max-upload-parts
                            optional: true
                  - name: NO_VERIFY_SSL
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: no-verify-ssl
                            optional: true
                  - name: DISABLE_SSL
                    valueFrom:
                        secretKeyRef:
                            name: pachyderm-storage-secret
                            key: disable-ssl
                            optional: true
                  - name: STORAGE_UPLOAD_CONCURRENCY_LIMIT
                    value: {{ .Values.pachd.storageUploadConcurrencyLimit | quote }}
                resources:
                  requests:
                    cpu: '{{ .Values.pachd.resources.requests.cpu }}'
                    memory: {{ .Values.pachd.resources.requests.memory }}
                {{- if .Values.pachd.resources.limits }}
                  limits:
                    cpu: '{{ .Values.pachd.resources.limits.cpu }}'
                    memory: {{ .Values.pachd.resources.limits.memory }}
                {{- end }}
                volumeMounts:
                  - name: pach-disk
                    mountPath: /pach
                  - name: pachyderm-storage-secret
                    mountPath: /pachyderm-storage-secret
                readinessProbe:
                    exec:
                        command:
                          - /pachd
                          - --readiness
                imagePullPolicy: {{ .Values.pachd.image.pullPolicy }}
            serviceAccountName: {{ include "pachyderm.serviceAccountName" . }}
