---
{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ include "pachyderm.fullname" . }}
    namespace: {{ .Release.Namespace }}
    labels:
        app: ""
        suite: pachyderm
        app.kubernetes.io/part-of: {{ include "pachyderm.fullname" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        helm.sh/chart: {{ include "pachyderm.chart" . }}
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ""
    resources:
      - nodes
      - pods
      - pods/log
      - endpoints
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
    apiGroups:
      - ""
    resources:
      - replicationcontrollers
      - services
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
    apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - pachyderm-storage-secret
{{- end }}
