---
{{- if .Values.rbac.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ include "pachyderm.fullname" . }}-worker
    namespace: {{ .Release.Namespace }}
    labels:
        app: ""
        suite: pachyderm
        app.kubernetes.io/part-of: {{ include "pachyderm.fullname" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        helm.sh/chart: {{ include "pachyderm.chart" . }}
rules:
  - verbs:
      - get
      - list
      - update
      - create
      - delete
    apiGroups:
      - ""
    resources:
      - services
{{- end }}
