---
{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ include "pachyderm.fullname" . }}-worker
    namespace: {{ .Release.Namespace }}
    labels:
        app: ""
        suite: pachyderm
        helm.sh/chart: {{ include "pachyderm.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: pachyderm
subjects:
  - kind: ServiceAccount
    name: {{ include "pachyderm.serviceAccountName" . }}-worker
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: ""
    kind: ClusterRole
    name: {{ include "pachyderm.fullname" . }}-worker
{{- end}}
